version: '2'

services:
  mariadb:
    container_name: 'mariadb4'
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  moodle:
    container_name: 'moodle4'
    image: 'bitnami/moodle:latest'
    ports:
      - '10004:80'
      - '9004:443'
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './apache_data:/bitnami/apache'
      - './php_data:/bitnami/php'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  apache_data:
    driver: local
